name: yolov4-gpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - scipy
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu==2.7.0rc0
    - opencv-python==4.1.1.26
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
    - scipy
